version: "3"
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${SHARE_LOCATION}/htpc/radarr/config:/config
      - ${SHARE_LOCATION}/downloads/movies:/movies
      - ${SHARE_LOCATION}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  
  radarr-addar:
    container_name: radarr-adder
    image: furman91/radarr-adder
    environment:
      - RADARR_IP=${RADARR_IP}
      - SONARR_IP=${RADARR_IP}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MANAGER_ID=${MANAGER_ID}
      - MANAGER_USERNAME=${MANAGER_USERNAME}
      - GF_USERNAME=${GF_USERNAME}
    restart: unless-stopped
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${SHARE_LOCATION}/htpc/sonarr/config:/config
      - ${SHARE_LOCATION}/downloads/tv:/tv
      - ${SHARE_LOCATION}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ${SHARE_LOCATION}/htpc/transmission/config:/config
      - ${SHARE_LOCATION}/downloads:/downloads
      - ${SHARE_LOCATION}/torrents_to_download:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - RUN_OPTS=run options here #optional
    volumes:
      - ${SHARE_LOCATION}/htpc/jackett/config:/config
      - ${SHARE_LOCATION}/torrents_to_download:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${SHARE_LOCATION}/htpc/bazarr/config:/config
      - ${SHARE_LOCATION}/downloads/movies:/movies
      - ${SHARE_LOCATION}/downloads/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${SHARE_LOCATION}/htpc/hydra2/config:/config
      - ${SHARE_LOCATION}/downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    network_mode: host
    volumes:
      - ./plex:/config
      - ${SHARE_LOCATION}/downloads/tv:/tv
      - ${SHARE_LOCATION}/downloads/movies:/movies
    restart: unless-stopped
